language: node_js

cache:
  - node_modules

steps:

  install:
    image: khs1994/node:git
    run:
      - npm install --registry=https://registry.npm.taobao.org --cache=/tmp/pcit_cache/npm

  script:
    run:
      - npm run build
      - mkdir -p ../public
      - cp -r ../public .
      - ls -la
      - ls -la public

  deploy_s3:
    image: pcit/s3
    if:
      status: success
      event: ['push']
    with:
      local_dir: public
      upload_dir: ui/nightly/${PCIT_COMMIT}
      region: 'us-east-1'
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}
      bucket: pcit
      endpoint: https://storage.khs1994.com
      use_path_style_endpoint: true
